# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
name: CI

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      # Install
      - name: Install
        run: yarn install
      # Build
      - name: Build
        run: CONTEXT=production yarn build
      # Validate
      - name: Validate
        run: yarn validate
      # Deploy Preview
      - name: Deploy Preview
        run: yarn deploy:preview --auth ${{secrets.NETLIFY_AUTH_TOKEN}}
        if: github.repository == 'fariapp/fari' && github.ref != 'refs/heads/master'
      # Deploy Production
      - name: Deploy Production
        run: yarn deploy:prod --auth ${{secrets.NETLIFY_AUTH_TOKEN}}
        if: github.repository == 'fariapp/fari' && github.ref == 'refs/heads/master'
